version: "3.9"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - static-data:/vol/web
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./env.dev
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    container_name: db
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - ./env.dev

volumes:
  db-data:
  static-data:
