# Generated by Django 3.2.16 on 2023-01-18 20:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='business_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
