# Generated by Django 3.2.16 on 2023-01-19 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, upload_to='media/businesses/%y/%m/%d'),
        ),
    ]
