# Generated by Django 3.2.16 on 2023-01-25 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20230123_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopper',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/shopper/%y/%m/%d'),
        ),
        migrations.CreateModel(
            name='MyCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=6, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.card')),
                ('shooper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shopper')),
            ],
        ),
    ]
