# Generated by Django 3.2.16 on 2023-01-25 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20230125_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mycards',
            old_name='shooper',
            new_name='shopper',
        ),
    ]
