# Generated by Django 3.2.16 on 2023-01-26 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_mycardshistory_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycards',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.card'),
        ),
        migrations.AlterField(
            model_name='mycards',
            name='shopper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shopper'),
        ),
    ]
