# Generated by Django 3.2.16 on 2023-01-27 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20230126_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycards',
            name='card',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='core.card'),
        ),
        migrations.AlterField(
            model_name='mycards',
            name='shopper',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='core.shopper'),
        ),
    ]
