# Generated by Django 3.2.16 on 2023-01-28 11:53

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_company_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopper',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.company_image_file_path),
        ),
        migrations.AddField(
            model_name='mycards',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.mycards_image_file_path),
        ),
    ]
