# Generated by Django 3.2.16 on 2023-02-02 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20230129_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycards',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.card'),
        ),
        migrations.AlterField(
            model_name='mycards',
            name='points',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='mycards',
            name='shopper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shopper'),
        ),
    ]
