# Generated by Django 3.2.17 on 2023-02-02 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20230202_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycards',
            name='image',
            field=models.ImageField(null=True, upload_to='mycards'),
        ),
    ]
